### ISSUE TITLE
Todo list/Bug list #2

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#459]
the previoud issue was getting too long so I'm adding the new bugs to a new issue.
this bug list is the bug list from whatsapp(the original list is by Alex).

also there are still 4 bugs in the old list (#396)

- [x]  CASE SENSITIVE in user anmde in login and signup. abd and Abd is not the same. - _it's okey that the user name is case sensitive. no bug here_

- [x] Complex search - the gui says it's in km but it actually in meters - fixed by Koral

- [x] big fonts  (#453)- fixed by Yael

- [x] avoid needing to re-enter the app after you allow the application access to your location - _not supported feature_

- [x] fix appearence of "upload image", the text of the button is getting cut

- [x] remove the back buttons in all pages - fixed by Yael

- [x] leaving a comment stuck on the spinner - fixed by Arthur

- [x] enable option to delete reviews. user should be able to delete his own reviews and admin should be able to delete every review he wants.

- [x] when getting out of the application the user is automatically logged out. it should stays logged in -_not supported feature_

- [x] in some places if the server is down the error is "undefined" we need to change it - fixed by Yael

- [x] remove back option from: ImgUpload, Admin and Userpage.

- [x] if uploading the image succes move back to the user page

- [x] leave review on street does not show the review after it's done

- [x] transfer all spinners to be the same as the spinner of Arthur

- [x] default rating in review

- [x] review if error was thrown, dismiss the spinner

- [x] remove unsued import client side

- [x] create final apk and make sure the services can access the server

- [x] update user guide

- [x] liking twice same review - spinner stuck

- [x] liking and then disliking stuck on a spinner

- [x] disliking cause minus 1 in the liking

- [x] Pinned Reviews - should appear fisrt and be bold somehow

**Comment by Kolikant** [comment]
It seems that nothing mentioned here is under classess or pages under my jurosdiction

**Comment by kapalex** [comment]
Edited a bit to remove things I already took care of since we made this list and were marked in #396

**Comment by ArthurSap** [comment]
Please verify for me that leaving a comment on a review doesn't keep the spinner stuck anymore.

**Comment by yaelAmitay** [comment]
@ArthurSap the spinner on comments doesn't stuck anymore :)

**Comment by koralchapnik** [comment]
when I've logged in as admin, and did like and then dislike to some review, the spinner didn't disappear.
@ArthurSap please pay attention
